### PR TITLE
Change test_train_split to train_test_split

### PR DESCRIPTION
**Pull request by orhankislal**

### CODE REVIEW

**Comment by fmcquillan99** [comment]
Thanks for this small but important change

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/madlib-pr-build/187/

**Comment by fmcquillan99** [comment]
doc/mainpage.dox.in still reads 
+    @defgroup grp_train_test_split Test Train Split

it should be 
+    @defgroup grp_train_test_split Train-Test Split

**Comment by iyerr3** [comment]
I'll make the change with the merge.

**Comment by fmcquillan99** [comment]
k, thx

**Pull request closed without merging**
