### PR TITLE
Fixed build errors by upgrading Boost from 1.47 to 1.61

### PR DESCRIPTION
**Pull request by make**
I had lots of build errors while trying to build MADlib for PostgreSQL 9.5 on Ubuntu Xenial 16.04.
Errors were related to boost.

```
markus@work:~/git/incubator-madlib/build$ make
[  1%] Built target EP_eigen
[  1%] Built target pythonFiles
[  2%] Built target EP_pyxb
[  3%] Built target EP_boost
[  3%] Built target sqlFiles
[  3%] Built target madlibPatches
[  8%] Built target madpackFiles
[  8%] Built target binaryFiles
[  8%] Built target configFiles
[ 28%] Built target sqlFiles_postgresql
[ 28%] Building CXX object src/ports/postgres/9.5/CMakeFiles/madlib_postgresql_9_5.dir/__/__/__/modules/regress/multilogistic.cpp.o
In file included from /home/markus/git/incubator-madlib/build/third_party/src/EP_boost/boost/fusion/sequence/io/detail/in.hpp:13:0,
                 from /home/markus/git/incubator-madlib/build/third_party/src/EP_boost/boost/fusion/sequence/io/in.hpp:13,
                 from /home/markus/git/incubator-madlib/build/third_party/src/EP_boost/boost/fusion/sequence/io.hpp:10,
                 from /home/markus/git/incubator-madlib/build/third_party/src/EP_boost/boost/fusion/tuple/tuple.hpp:16,
                 from /home/markus/git/incubator-madlib/build/third_party/src/EP_boost/boost/fusion/tuple.hpp:10,
                 from /home/markus/git/incubator-madlib/build/third_party/src/EP_boost/boost/fusion/include/tuple.hpp:10,
                 from /home/markus/git/incubator-madlib/build/third_party/src/EP_boost/boost/tr1/tuple.hpp:58,
                 from /home/markus/git/incubator-madlib/src/ports/postgres/dbconnector/dbconnector.hpp:87,
                 from /home/markus/git/incubator-madlib/src/modules/regress/multilogistic.cpp:11:
/home/markus/git/incubator-madlib/build/third_party/src/EP_boost/boost/fusion/sequence/io/detail/manip.hpp:86:21: error: reference to ‘basic_string’ is ambiguous
             typedef FUSION_STRING_OF_STREAM(Stream) string_type;
                     ^

...(lots of errors)

src/ports/postgres/9.5/CMakeFiles/madlib_postgresql_9_5.dir/build.make:62: recipe for target 'src/ports/postgres/9.5/CMakeFiles/madlib_postgresql_9_5.dir/__/__/__/modules/regress/multilogistic.cpp.o' failed
make[2]: *** [src/ports/postgres/9.5/CMakeFiles/madlib_postgresql_9_5.dir/__/__/__/modules/regress/multilogistic.cpp.o] Error 1
CMakeFiles/Makefile2:747: recipe for target 'src/ports/postgres/9.5/CMakeFiles/madlib_postgresql_9_5.dir/all' failed
make[1]: *** [src/ports/postgres/9.5/CMakeFiles/madlib_postgresql_9_5.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```
Fixed errors by upgrading Boost from 1.47 to 1.61.

### CODE REVIEW

**Comment by logsanctuary** [comment]
Hello,

In debian jessie 8 with postgres 9.4 : 

...
[ 28%] [ 28%] No update step for 'EP_boost'
No patch step for 'EP_boost'
[ 28%] Performing configure step for 'EP_boost'
Ignored: cmake -GUnix Makefiles /home/jmmetzger/incubator-madlib/build/third_party/src/EP_boost
[ 28%] Performing build step for 'EP_boost'
Ignored: make
[ 28%] Performing install step for 'EP_boost'
Ignored: make
[ 28%] Completed 'EP_boost'
make[3]: Leaving directory '/home/test/incubator-madlib/build'
[ 28%] Built target EP_boost
make[2]: Leaving directory '/home/test/incubator-madlib/build'
Makefile:137: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/test/incubator-madlib/build'
Makefile:5: recipe for target 'all' failed
make: *** [all] Error 2

Maybe is the same error ???

**Comment by make** [comment]
@fmcquillan99 Release 1.9.1 cannot be compiled on the Ubuntu 16.04 LTS due to errors above. Upgrading the boost to the newest version 1.61 resolves the problem for me. Is this solution correct? Any plans to merge this PR?

**Comment by mktal** [comment]
@make @fmcquillan99  Thanks for the PR. We are testing it right now and will merge if all tests pass.

**Comment by logsanctuary** [comment]
Hello asfgit, there are the same error after the commit :

Linking CXX shared module lib/libmadlib.so
[ 44%] Built target madlib_postgresql_9_4
Scanning dependencies of target pythonFiles_postgresql_9_4
[ 44%] Preprocessing pca/pca.py_in with m4.
/bin/sh: 1: Syntax error: "(" unexpected
src/ports/postgres/9.4/CMakeFiles/pythonFiles_postgresql_9_4.dir/build.make:146: recipe for target 'src/ports/postgres/9.4/modules/pca/pca.py' failed
make[2]: *** [src/ports/postgres/9.4/modules/pca/pca.py] Error 2
CMakeFiles/Makefile2:797: recipe for target 'src/ports/postgres/9.4/CMakeFiles/pythonFiles_postgresql_9_4.dir/all' failed
make[1]: *** [src/ports/postgres/9.4/CMakeFiles/pythonFiles_postgresql_9_4.dir/all] Error 2
Makefile:137: recipe for target 'all' failed
make: *** [all] Error 2

**Pull request closed without merging**
