### PR TITLE
Elastic_net: Fix grouping without normalization bug

### PR DESCRIPTION
**Pull request by njayaram2**
JIRA: MADLIB-1146

Selecting grouping columns into the output table was not working
when data was NOT scaled, but grouping was used. This commit
fixes it.

Closes #172

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/madlib-pr-build/168/

**Comment by njayaram2** [comment]
jenkins ok to test

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/madlib-pr-build/169/

**Comment by njayaram2** [comment]
jenkins ok to test

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/madlib-pr-build/170/

**Comment by njayaram2** [comment]
jenkins ok to test

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/madlib-pr-build/178/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/madlib-pr-build/181/

**Pull request closed without merging**
