### PR TITLE
CI: Add concourse scripts for testing with GPDB.

### PR DESCRIPTION
**Pull request by orhankislal**
Fix kmeans IC drop schema issue.

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/madlib-pr-build/93/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/madlib-pr-build/94/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/madlib-pr-build/96/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/madlib-pr-build/100/

**Comment by orhankislal** [comment]
Closing the pull request since the proposed pipeline is too dependent on the GPDB scripts.

**Pull request closed without merging**
