### PR TITLE
Update RELEASE_NOTES for v1.12 release

### PR DESCRIPTION
**Pull request by orhankislal**

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/madlib-pr-build/155/

**Comment by fmcquillan99** [comment]
Here are some suggested changes/additions:

1) Change release date to Fri Aug 18 which might be a better estimate.

2) MLP
Change
New Module: Multilayer Perceptron (MADLIB-413)
to
New Module: Multilayer Perceptron (MADLIB-413, MADLIB-1134)

3) APSP
Change
New module: Graph - All Pairs Shortest Path (MADLIB-1099)
to
New module: Graph - All Pairs Shortest Path (MADLIB-1072, MADLIB-1099, MADLIB-1106)

4) WCC
Change
New module: Graph - Weakly Connected Components (MADLIB-1071, MADLIB-1083)
to 
New module: Graph - Weakly Connected Components (MADLIB-1071, MADLIB-1083, MADLIB-1101)

5) Summary
Change
Summary: Allow user to determine the number of columns per run (MADLIB-1117)
to
Summary: 
  - Allow user to determine the number of columns per run (MADLIB-1117)
  - Improve efficiency of computation time by ~35% (MADLIB-1104)

6) TLP
Updates for Apache Top Level Project readiness (MADLIB-1130, MADLIB-1133)
* what about MADLIB-1132 and MADLIB-1142
* also add the epic MADLIB-1112

7) Train-test split
Add:
 New Module: Sample - Train-test split (MADLIB-1119)

8) under the bugs section:
Change
- Fix the data scaling bug with normalization
to
- Fix the data scaling bug with normalization (MADLIB-1094)

9) under the bugs section:
change:
Update 'optimizer' GUC only if editable
to
Update 'optimizer' GUC only if editable (MADLIB-1109)

10) Change
Promote cardinality estimators to top level module from early stage 
to
Promote cardinality estimators to top level module from early stage (MADLIB-1120)

11) Under bugs section:
change
Graph: Quoted output table name does not work for some modules
to
Graph: Quoted output table name does not work for some modules (MADLIB-1137)

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/madlib-pr-build/156/

**Comment by iyerr3** [comment]
please retest

**Comment by iyerr3** [comment]
test this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/madlib-pr-build/159/

**Pull request closed without merging**
